### ISSUE TITLE
http://diaporama.glsl.io/ is dead

### ISSUE THREAD

**Issue by catskul** [gre/diaporama-videos-example#1]
Looks like it's parked.

![image](https://cloud.githubusercontent.com/assets/375302/26279424/6f7ef48e-3d81-11e7-928e-b109f5bb4881.png)

**Comment by gre** [comment]
this repository track the diaporama website which is still hosted in http://greweb.me/diaporama/

for glsl.io , see https://github.com/gre/transitions.glsl.io/issues/100 – I didn't renew the domain which then was cybersquatted..

diaporama.glsl.io was a demo that, really could have been statically hosted too, but also it should be easy to run it in local: https://github.com/gre/diaporama-maker

i didn't renew glsl.io (that was mainly hosting the glsl transitions) but fortunately i'm working right now on a new version of the idea that I should release soon
